language: rust
rust: nightly
before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
install:
    - sudo apt-get install gcc-arm-none-eabi
script:
    - ./configure --host=arm-none-eabi
    - cargo build --target=$TARGET --verbose --features $PLATFORM
    - ./ci/build-examples.sh
after_script:
    - cargo test --lib --verbose
    - (cd ./ioreg; cargo build --verbose; cargo test --verbose)
    - (cd ./platformtree; cargo build --verbose; cargo test --verbose)
    - (cd ./macro_platformtree; cargo build --verbose; cargo test --verbose)
env:
  matrix:
    - PLATFORM=lpc17xx
      TARGET=thumbv7m-none-eabi
      EXAMPLES="blink blink_pt uart dht22 empty"
    - PLATFORM=k20
      TARGET=thumbv7em-none-eabi
      EXAMPLES="blink_k20 blink_k20_isr"
    - PLATFORM=stm32f4
      TARGET=thumbv7em-none-eabi
      EXAMPLES="blink_stm32f4"
    - PLATFORM=stm32l1
      TARGET=thumbv7m-none-eabi
      EXAMPLES="blink_stm32l1 bluenrg_stm32l1 usart_stm32l1"
